### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZiNT3X** [omerb124/bulkMobileFriendly#1]
Hello, 

sometimes i get this error.

I'm Python beginner, actually yesterday I started using it.

Thanks for any help, I love using your script just this error sometimes happens.

Original code wasn't changed so much, I only added filtering and saving to broken.txt and failed.txt but I don't think its any problem with that.

Here is log from cmd:

`Traceback (most recent call last):
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "checker-1.py", line 123, in <module>
    __main__()
  File "checker-1.py", line 110, in __main__
    if(not is_url_friendly(url)):
  File "checker-1.py", line 38, in is_url_friendly
    data = requests.get(url).text
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\---------\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)`

**Comment by ZiNT3X** [comment]
Actually my failure, i ended script becouse I thought its not working, but I forgot add print to script so it looked like freezed and got this err when I manually ended it.

**Comment by omerb124** [comment]
Glad you fixed it!
feel free to ask questions :)

**Comment by ZiNT3X** [comment]
I think thats all, thank you 👍
